<a href="https://colab.research.google.com/github/vmatthews3/DataScience/blob/main/Day1_IntroToPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# An introduction to Python
In this course, we will be mostly using Python to solve equations, analyse data and run simulations. You can think of it as a calculator that allows us to perform a wide range of things. For this reason, you'll have to learn the appropriate syntax, that is, how to type the instructions so that the computer can appropriately interpret them.

Today, we will start with an introduction to Python using iPython notebooks. There are a few basics you need to know:

*   The code, that is, your instructions, is written in "cells" or "blocks". Each cell will contain a certain number of instructions. You can create a new code cell by clicking on **+ Code** or a text cell (like this one) by clicking on **+ Text**.
*   To execute the instructions in a code cell you must "run" the cell. If you do that, all the instructions in a single cell will be executed. In order to run a cell, you must click the ▶ button on the left of the cell, or press **Shift+Enter**.
*   All the lines in a code cell will be interpreted as Python instructions, with one exception! Any line starting with a hash # will be ignored. You can use that to write explanatory notes about your code. 

We will now walk you through some of the basics of Python notebooks. 
The easiest way you can use cells is as a calculator (make sure you remember the order of operations). After running the cell, you should be able to see the result of the calculation right below.

In [1]:
2 * 5 - 9

1

If you write more than one operation in a cell, you'll only be able to see the result of the last operation.

In [ ]:
3 - 9 / 6
10 / 4

2.5

The first and most important command you need to know is `print`. It takes in any number of inputs, and prints them out on one line of text:

In [ ]:
# this line is just a comment, so the computer ignores it 
# the line below prints a sentence
print("Hello World! Here is some code.")

# the line below prints the result of 2 + 2 * 3
print(2 + 2 * 3)

Hello World! Here is some code.
8


## Variables and Operations

Variables are "containers" for storing data values. Think of a variable as a name attached to a particular object. In Python, variables need not be declared or defined in advance, as is the case in many other programming languages. To create a variable, you just assign it a value and then start using it.

In [ ]:
# assign to a the value 1
a = 1
# assign to b the value 2
b = 2
# assign to c the value of a + b
c = a + b
# print the values of a, b and c
print('a =',a,' b =',b,' c =',c)

a = 1  b = 2  c = 3


Variables have types: a word and a number are not the same. To see more information about what is stored in a variable, you can use the built-in `type()` function:

In [ ]:
# example of a string
ex_str = "hello"
# example of an integer
ex_int = 2
# example of a decimal number
ex_float = 2.5
# example of a boolean (true or false) value
ex_bool = True
# example of a list of values 
ex_list = [1, 2, 3, "four", False]

# print on the screen these values and their types
print(ex_str," is a string", type(ex_str))
print(ex_int," is an integer ", type(ex_int))
print(ex_float," is a float", type(ex_float))
print(ex_bool," is a boolean", type(ex_bool))
print(ex_list," is a list", type(ex_list))

hello  is a string <class 'str'>
2  is an integer  <class 'int'>
2.5  is a float <class 'float'>
True  is a boolean <class 'bool'>
[1, 2, 3, 'four', False]  is a list <class 'list'>


## Libraries
A library is a collection of codes that can be used later on in a program for some specific well-defined operations. It is important to know that Python doesn't automatically load all existing functions in the world, so in order to allow Python to use certain functions, one must load the corresponding library. Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

*   To import a library, use the syntax `import library`
*   You can give an alias to the library to simplify the code. To do so, use `import library as alias`

Here are some libraries we will be using today

*   **Math** is a module that provides access to the mathematical functions
*   **NumPy** is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices: `import numpy as np`
*   **SymPy** is a Python library for symbolic mathematics. We will use an alias again: `import sympy as sp`

When using functions in libraries, they have to be preceeded by the library name:

In [ ]:
# import math operations library "math"
import math
print(math.log(10))
print(math.tanh(9))

2.302585092994046
0.999999969540041


### Vectors and Matrices
Vectors in Python can be represented as lists using square brackets `[]`. For example, the vector 
$$v_1=\begin{bmatrix} 1\\ 2 \\ 3 \end{bmatrix}$$ 
can be defined as `v1 = [1, 2, 3]`. However, this is not the only or best way to represent a vector in Python. Instead, it will be more convenient to declare it as a NumPy array; to do so we write `v2 = np.array([1, 2, 3])`. 

Similarly, a matrix is represented as a vector of vectors. For example, the matrix
$$v_1=\begin{bmatrix} 1 & 0 & 3\\ 1 & 2 & 0 \\ 0 & 3 & 1 \end{bmatrix}$$
can be represented as a NumPy array `m = np.array([[1, 0, 3],[1, 2, 0],[0, 3, 1]])`.

In [ ]:
# this is a the vector (1, 2, 3)
v1 = [1, 2, 3]

# import numpy library and call it "np"
import numpy as np

# the same vector as v1, but now as a numpy array
v2 = np.array([1, 2, 3])

# this is a matrix
m = np.array([[1, 0, 3],[1, 2, 0],[0, 3, 1]])

print(v1)
print(v2)
print(m)

[1, 2, 3]
[1 2 3]
[[1 0 3]
 [1 2 0]
 [0 3 1]]


Lists can be accessed at specific indices, sliced and modified in many different ways. To access values in lists, use the square brackets for slicing along with the index or indices to obtain value available at that index. Note that in Python, the **indexing starts at 0**. For example:

In [ ]:
# access the first element in v2
print(v2[0])

# slice from positions 0 - 1 in v2
print(v2[0:2])

# element in second row and third colum in m
print(m[1,2])

1
[1 2]
0


You can update single or multiple elements of lists by giving the slice on the left-hand side of the assignment operator.

In [ ]:
print(v2)
v2[2] = 10
print("New value available at index 2 : ")
print(v2)

[1 2 3]
New value available at index 2 : 
[ 1  2 10]


NumPy arrays allow to perform mathematical operations such as addition/substraction, matrix multiplication, dot product, etc. That is not possible with regular Python lists. 

In [ ]:
u1 = np.array([1, 2, 3])
u2 = np.array([4, 5, 6])
m1 = np.array([[3, 2, 1],[0, 1, 3]])
# addition/substraction
print(u1 + u2)
print(u1 - u2)

# multiplication by scalar
print(3 * u1)

# dot product
print(np.dot(u1, u2))

# matrix times vector
print(np.matmul(m1, u1))
print(np.matmul(m1, u2))

[5 7 9]
[-3 -3 -3]
[3 6 9]
32
[10 11]
[28 23]


## Today's Application: Solving Linear Systems
Here we will show two ways of solving linear systems in Python using two different libraries: **NumPy** and **SymPy**. Each library has advantatges and disatvantages.

As our first example, let's take a look at the following system:
$$\begin{cases}2x+y=9 \\ x+3y=2\end{cases}$$

In [ ]:
# using NumPy
import numpy as np

# we use the variables m, b to represent the system mx = b, and r the result
m = np.array([[2,1],[1,3]])
b = np.array([9,2])

# we use the built-in NumPy function linalg.solve()
r = np.linalg.solve(m, b)
print(r)

[ 5. -1.]


In [ ]:
# Using SymPy
import sympy as sp

# the syntax is different here. We first must tell the computer the symbols we are using as variables. 
x, y = sp.symbols('x,y')

# here we use the built-in SymPy function solve()
r = sp.solve([2*x + y - 9, x + 3*y - 2])
print(r)

{x: 5, y: -1}


Let's look at another example:
$$\begin{cases}3x+y=9 \\ 6x+2y=18\end{cases}$$
In this case, it is not hard to check that the system has infinitely many solutions. You can easily see that the second equation is just twice the first one. If we attempt to solve it using NumPy, it will produce an error. SymPy, instead, will give you an answer with $x$ in terms of $y$, indicating that there isn't a unique solution. 

In [ ]:
# since we already loaded the libraries, we don't need to import again
# using NumPy
m = np.array([[3,1],[6,2]])
b = np.array([9,18])
r = np.linalg.solve(m, b)
print(r)

LinAlgError: ignored

In [ ]:
# using SymPy.
r = sp.solve([3*x + y - 9, 6*x + 2*y - 18])
print(r)

{x: 3 - y/3}


## Homework
Some of the homework problems require you to solve linear systems. You may use the cells below to do that. Here are some tips:
*   When using `SymPy`, make sure you define all the symbolic variables you need. You can use x1, x2, x3, etc. instead of x, y, z, etc., so that you don't run out of symbols. 
*   Make sure that your variables storing the values of the matrix and solution are defined as needed before running the solving functions.

In [3]:
#Question 4, problem 3 in Sports Rating

import numpy as np

m = np.array([[6,-2,0,-2],[-2,6,-2,0],[0,-2,6,-2],[-2,0,-2,6]])
b = np.array([3,1,1,-1])

r = np.linalg.solve(m, b)
print(r)

[0.76666667 0.56666667 0.43333333 0.23333333]


In [1]:
# import sympy 
from sympy import * 

M = Matrix([[0,0,0,0,0,0,1/3,0,],[1/2,0,1/2,1/3,0,0,0,0],[1/2,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1/2,1/3,0,0,1/3,0],[0,0,0,1/3,1/3,0,0,1/2],[0,0,0,0,1/3,0,0,1/2],[0,0,0,0,1/3,1,1/3,0]])
   
M_rref = M.rref()  

print(format(M_rref))


(Matrix([
[1, 0, 0, 0, 0, 0, 0,    0],
[0, 1, 0, 0, 0, 0, 0,    0],
[0, 0, 1, 0, 0, 0, 0,    0],
[0, 0, 0, 1, 0, 0, 0,    0],
[0, 0, 0, 0, 1, 0, 0,  1.5],
[0, 0, 0, 0, 0, 1, 0, -0.5],
[0, 0, 0, 0, 0, 0, 1,    0],
[0, 0, 0, 0, 0, 0, 0,    0]]), (0, 1, 2, 3, 4, 5, 6))
